package control

import "text/template/parse"

// Preprocessor defines the general preprocessor for hcl control structures
type Preprocessor struct {
	Data     []byte
	Switches []*Switch
}

// NewPreprocessor will generate a new preprocessor
func NewPreprocessor(data []byte) *Preprocessor {
	return &Preprocessor{Data: data}
}

// TransformNode will evalute any switch statement at the current node and
// return the evaluated inner node along with any additional nodes that were
// generated by the control structure
func (p *Preprocessor) TransformNode(n *parse.Node) ([]*parse.Node, error) {
	return nil, nil
}

// NeedsTransform returns true if the node requires transformation (e.g. if it
// is a switch statement)
func (p *Preprocessor) NeedsTransform(n *parse.Node) bool {
	return false
}
