// Copyright © 2016 Asteris, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package control

import "text/template/parse"

// Preprocessor defines the general preprocessor for hcl control structures
type Preprocessor struct {
	Data     []byte
	Switches []*Switch
}

// NewPreprocessor will generate a new preprocessor
func NewPreprocessor(data []byte) *Preprocessor {
	return &Preprocessor{Data: data}
}

// TransformNode will evalute any switch statement at the current node and
// return the evaluated inner node along with any additional nodes that were
// generated by the control structure
func (p *Preprocessor) TransformNode(n *parse.Node) ([]*parse.Node, error) {
	return nil, nil
}

// NeedsTransform returns true if the node requires transformation (e.g. if it
// is a switch statement)
func (p *Preprocessor) NeedsTransform(n *parse.Node) bool {
	return false
}
